### ISSUE TITLE
Invalid bind address format: port is required

### ISSUE THREAD

**Issue by rizerzero** [Tecnativa/docker-socket-proxy#51]
Hi, I had an error message when I export the socket endpoint as described in the documentation 
`export DOCKER_HOST=tcp://localhost`

```
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 72, in main
  File "compose/cli/main.py", line 125, in perform_command
  File "compose/cli/command.py", line 76, in project_from_options
  File "compose/cli/command.py", line 142, in get_project
  File "compose/cli/docker_client.py", line 47, in get_client
  File "compose/cli/docker_client.py", line 141, in docker_client
  File "site-packages/docker/context/context.py", line 26, in __init__
  File "site-packages/docker/context/config.py", line 77, in get_context_host
  File "site-packages/docker/utils/utils.py", line 281, in parse_host
docker.errors.DockerException: Invalid bind address format: port is required: tcp://localhost
[12211] Failed to execute script docker-compose
```

I'm not sure if the documentation should be updated to export the endpoint with the port.
``export DOCKER_HOST=tcp://localhost:2375``

**Comment by joao-p-marques** [comment]
Hi, thanks for reporting this @rizerzero 
Maybe docker changed this recently, but also, the documentation could be more precise, indeed...
I already added a PR to fix it :+1:
